[package]
name = "phylo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version="4.5.4", optional=true}
itertools = "0.11.0"
num = "0.4.1"

[features]
build-binary = ["clap"]

[[bin]]
name = "phylo-rs"
path = "src/bin.rs"
required-features = ["build-binary"]

[lib]
name = "phylo"
path = "src/lib.rs"
